### Numpy

In [45]:
import numpy as np

In [46]:
arr=np.array([1,2,3,4,6])
arr

array([1, 2, 3, 4, 6])

In [47]:
list_of_lists=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [49]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [56]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [57]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [58]:
np.random.rand(2,5)

array([[0.37965981, 0.5461443 , 0.50455109, 0.18872145, 0.39632491],
       [0.23638254, 0.28295842, 0.32321398, 0.3993133 , 0.93035921]])

In [59]:
np.random.randn(2,5)

array([[ 0.58065695,  0.92654367,  1.66790784,  0.56916628,  0.49122004],
       [-1.18206905, -0.51283074, -0.9519517 ,  0.80406277,  0.0764302 ]])

In [60]:
np.random.randint(1,10)

3

In [61]:
np.random.randint(1,10,100)

array([7, 9, 3, 2, 8, 3, 1, 2, 5, 5, 9, 1, 1, 5, 3, 4, 2, 1, 8, 3, 2, 4,
       9, 5, 7, 7, 5, 5, 4, 8, 1, 1, 8, 9, 3, 6, 6, 1, 5, 4, 7, 6, 2, 8,
       7, 8, 6, 4, 7, 8, 6, 3, 8, 3, 2, 5, 2, 9, 3, 6, 5, 5, 2, 5, 6, 7,
       6, 9, 2, 3, 7, 9, 6, 6, 5, 6, 9, 5, 4, 2, 8, 6, 1, 1, 9, 3, 2, 9,
       1, 6, 5, 5, 8, 1, 4, 7, 9, 5, 1, 7])

In [62]:
np.random.randint(10,1)

ValueError: low >= high

In [ ]:
sample_array=np.arange(30)
sample_array

In [ ]:
sample_array.reshape(5,6)

In [ ]:
sample_array.reshape(5,4)

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

In [ ]:
rand_array.min()

In [ ]:
rand_array.max()

In [ ]:
rand_array.argmin()

In [ ]:
rand_array.argmax()

In [ ]:
a=np.random.rand(2,3)
a

In [ ]:
a.T

In [ ]:
sample_array=np.arange(10,21)
sample_array

In [ ]:
sample_array[0]

In [ ]:
sample_array[2:5]

In [ ]:
sample_matrix=np.array(([1,56,34],[34,54,87],[67,90,100]))

In [ ]:
sample_matrix

In [ ]:
sample_matrix[2][2]

In [ ]:
sample_matrix[2]

In [ ]:
sample_matrix[1,:]

In [ ]:
sample_matrix[0,0:2]

In [ ]:
sample_array=np.arange(1,10)

In [ ]:
sample_array

In [ ]:
sample_array+sample_array

In [ ]:
np.log(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.sqrt(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.exp(sample_array)

In [ ]:
np.average(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.var(sample_array)

In [ ]:
np.mean(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
array=np.random.randn(3,6)
array

In [ ]:
np.round(array,decimals=3)

In [ ]:
sports=np.array(['golf','cricket','football','golf','basketball','Golf','Golf'])
np.unique(sports)

### Pandas

In [ ]:
import pandas as pd

In [ ]:
labels=['w','x','y','z']
sample_list=[1,2,3,4]
array=np.array([10,11,12,13])
dict={'a':1,'b':2,'y':3,'z':4}

In [ ]:
pd.Series(data=array)

In [ ]:
pd.Series(data=sample_list,index=labels)

In [ ]:
pd.Series(array,labels)

In [ ]:
pd.Series(dict)

In [ ]:
sports1=pd.Series([1,2,3,4],index=["Cricket","Fball","Golf","Basketball"])
sports1

In [ ]:
sports2=pd.Series([11,21,5,6],index=["Cricket","Baseball","Golf","basketball"])
sports2

In [ ]:
sports1+sports2

In [ ]:
df=pd.DataFrame(np.random.rand(6,5),index='A B C D E F'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())

In [ ]:
df

In [ ]:
df={'Id':[100,101,102,103],'Name':['a','b','c','d'],'Marks':[87,23,67,19]}
df1=pd.DataFrame(df)
df1

## Importing Dataset using Pandas

In [5]:
import numpy as np
import pandas as pd

In [9]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/HHE_MA_July31_Batch/main/loan_prediction.csv")

In [10]:
df.shape

(614, 13)

In [15]:
df.head(15)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0   LP001002   Male      No          0      Graduate            No   
1   LP001003   Male     Yes          1      Graduate            No   
2   LP001005   Male     Yes          0      Graduate           Yes   
3   LP001006   Male     Yes          0  Not Graduate            No   
4   LP001008   Male      No          0      Graduate            No   
5   LP001011   Male     Yes          2      Graduate           Yes   
6   LP001013   Male     Yes          0  Not Graduate            No   
7   LP001014   Male     Yes         3+      Graduate            No   
8   LP001018   Male     Yes          2      Graduate            No   
9   LP001020   Male     Yes          1      Graduate            No   
10  LP001024   Male     Yes          2      Graduate            No   
11  LP001027   Male     Yes          2      Graduate           NaN   
12  LP001028   Male     Yes          2      Graduate            No   
13  LP001029   Male      No          0      Graduate            No   
14  LP001030   Male     Yes          2      Graduate            No   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              5849                0.0         NaN             360.0   
1              4583             1508.0       128.0             360.0   
2              3000                0.0        66.0             360.0   
3              2583             2358.0       120.0             360.0   
4              6000                0.0       141.0             360.0   
5              5417             4196.0       267.0             360.0   
6              2333             1516.0        95.0             360.0   
7              3036             2504.0       158.0             360.0   
8              4006             1526.0       168.0             360.0   
9             12841            10968.0       349.0             360.0   
10             3200              700.0        70.0             360.0   
11             2500             1840.0       109.0             360.0   
12             3073             8106.0       200.0             360.0   
13             1853             2840.0       114.0             360.0   
14             1299             1086.0        17.0             120.0   

    Credit_History Property_Area Loan_Status  
0              1.0         Urban           Y  
1              1.0         Rural           N  
2              1.0         Urban           Y  
3              1.0         Urban           Y  
4              1.0         Urban           Y  
5              1.0         Urban           Y  
6              1.0         Urban           Y  
7              0.0     Semiurban           N  
8              1.0         Urban           Y  
9              1.0     Semiurban           N  
10             1.0         Urban           Y  
11             1.0         Urban           Y  
12             1.0         Urban           Y  
13             1.0         Rural           N  
14             1.0         Urban           Y

In [14]:
df.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [21]:
df.sample(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
131  LP001473   Male      No          0      Graduate            No   
14   LP001030   Male     Yes          2      Graduate            No   
132  LP001478   Male      No          0      Graduate            No   
235  LP001784   Male     Yes          1      Graduate            No   
364  LP002180   Male      No          0      Graduate           Yes   
566  LP002836   Male      No          0      Graduate            No   
256  LP001849   Male      No          0  Not Graduate            No   
209  LP001702   Male      No          0      Graduate            No   
441  LP002409   Male     Yes          0      Graduate            No   
477  LP002530    NaN     Yes          2      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
131             2014             1929.0        74.0             360.0   
14              1299             1086.0        17.0             120.0   
132             2718                0.0        70.0             360.0   
235             5500             1260.0       170.0             360.0   
364             6822                0.0       141.0             360.0   
566             3333                0.0        70.0             360.0   
256             6045                0.0       115.0             360.0   
209             3418                0.0       127.0             360.0   
441             7901             1833.0       180.0             360.0   
477             2873             1872.0       132.0             360.0   

     Credit_History Property_Area Loan_Status  
131             1.0         Urban           Y  
14              1.0         Urban           Y  
132             1.0     Semiurban           Y  
235             1.0         Rural           Y  
364             1.0         Rural           Y  
566             1.0         Urban           Y  
256             0.0         Rural           N  
209             1.0     Semiurban           N  
441             1.0         Rural           Y  
477             0.0     Semiurban           N

In [19]:
df.shape[1]

13

In [25]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [27]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [28]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [29]:
df.describe(include="all")

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN

In [32]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')